// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WildFireTracker.search;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260921081109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WildFireTracker.fires.FireDetectionParsing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("acq_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("acq_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("acquired_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("bright_ti4")
                        .HasColumnType("double precision");

                    b.Property<double>("bright_ti5")
                        .HasColumnType("double precision");

                    b.Property<string>("confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("daynight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("frp")
                        .HasColumnType("double precision");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("satellite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("latitude", "longitude", "acquired_at", "satellite")
                        .IsUnique();

                    b.ToTable("FireDetections");
                });
#pragma warning restore 612, 618
        }
    }
}
