name: "Ping Render Service"

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: 'Ping service'
        run: curl -I https://fire-tracker-yh7z.onrender.com/ping
  
